### ISSUE TITLE
LtiConstants.php contains both http and https url

### ISSUE THREAD

**Issue by kanipk** [packbackbooks/lti-1-3-php-library#103]
LtiConstants.php file contains both http and https urls. Is there any specific reason for that?

![screenshot-sonarcloud io-2023 09 26-12_30_32](https://github.com/packbackbooks/lti-1-3-php-library/assets/17844529/fe12b9c0-b56f-4788-9b6d-451e75125751)

**Comment by dbhynds** [comment]
That's a great question for 1EdTech / IMSGlobal. I have no idea why they chose these naming conventions:

- Using http: https://www.imsglobal.org/spec/lti/v1p3/#role-vocabularies
- Using https: https://www.imsglobal.org/spec/lti-ags/v2p0/#line-item-service-scope-and-allowed-http-methods

However, these aren't being used for cross-platform communication in any way. Judging from the screenshot you provided, it looks like this was something flagged up by an automated security scanner. These strings are used as keys in json payloads in the JWT sent over in LTI message launches (and other https-based communication). As such they can be safely ignored by the security scanner. Nothing is directly curling these URLs. See an example json object: https://www.imsglobal.org/spec/lti-ags/v2p0/#example-service-claims

<img width="846" alt="Screenshot 2023-10-03 at 22 10 28" src="https://github.com/packbackbooks/lti-1-3-php-library/assets/849626/f7149fbd-9b3b-407a-aa27-fd41ac37e366">
