### ISSUE TITLE
DeepLinkResource iframe - need for src parameter?

### ISSUE THREAD

**Issue by cmcfadden** [packbackbooks/lti-1-3-php-library#108]
Thanks for all your work on this, it's a great project. My read of the [deep linking](https://www.imsglobal.org/spec/lti-dl/v2p0#content-item-types) spec implies that the `LtiDeepLinkResourceIframe` should have a `src` parameter, which is used to reference the actual target for the iframe. It seems like Canvas won't render an iframe if that's not present. I'm happy to throw up a PR, but I wanted to check if that seems like the right interpretation first?

**Comment by dbhynds** [comment]
I agree with your assessment. Open a PR and assign me to it. I'll take a look quickly.
