### ISSUE TITLE
Unable to get public key if 'alg' not present in platform jwks

### ISSUE THREAD

**Issue by snake** [packbackbooks/lti-1-3-php-library#50]
I realise this is a php-jwt issue (https://github.com/firebase/php-jwt/blob/main/src/JWK.php#L86-L89) AND one that presents itself in a version of php-jwt that isn't yet supported here -  but it appears to result in this library being unable to launch tools from D2L, which apparently won't provide the alg in their JWKS JSON (I can't verify the D2L specifics locally - a community member reported that -  but can certainly see the issue if I configure a dockerised Canvas instance to omit the alg field). 

Just wondering if a workaround is required in D2L perhaps? Are others using this library successfully with D2L without issue? I'm reluctant to put a hack in place, but I suspect that perhaps we could assume a value of RS256 when kty=RSA and alg is omitted (as in https://github.com/BookStackApp/BookStack/issues/3206), though it certainly feels quite dirty. 

I suspect this will impact the pull request https://github.com/packbackbooks/lti-1-3-php-library/pull/46 also, since that's what we're using when we see the issue here.

**Comment by dbhynds** [comment]
We are successfully using this library with D2L. (We have a couple dozen D2L integrations.) That said, D2L continues to be the most difficult of the major LMSes to integrate with. I'll do some research into the issue and get back to you.

**Comment by snake** [comment]
Thanks for the reply. Yep, it'll only be an issue if/when php-jwt dependency is updated to 6.0+. Sorry if that wasn't clear. We've since patched the library downstream to work around this when using pwp-jwt 6.0.

**Comment by dbhynds** [comment]
Thanks for your patience. I finally got the other PR merged in, and am turning my attention to this next.

> We've since patched the library downstream to work around this when using pwp-jwt 6.0.

Mind sharing what your patch looks like? Is it essentially something like this to the LtiMessageLaunch?

```php
if (!isset($jwt['header']['alg'])) $jwt['header']['alg'] = 'RSA256';
```

**Comment by snake** [comment]
Sure thing. Here's the commit we're using in Moodle. It's not so much a case of a missing 'alg' in the JWT header (I've not seen that happening), rather, it's dealing with the missing 'alg' property in the JWKS JSON (where 'alg' may be omitted). I've inferred it from the header in the JWT in such cases, provided it's safe to do so (simple check matching those asymmetric algs supported by LTI).
https://github.com/snake/lti-1-3-php-library/commit/fcfaacae84b72d0409d5fe181bea8ed761d536eb
