### ISSUE TITLE
Should I have to provide new instances of the Lti13Database, Lti13Cookie, Lti13Cache and LtiServiceConnector whenever I call LtiOidcLogin or LtiMessageLaunch?

### ISSUE THREAD

**Issue by theotherdy** [packbackbooks/lti-1-3-php-library#56]
I have a feeling that I am missing something fundamental as a Laravel noob but I seem to have to pass new instances of Lti13Database, Lti13Cookie, and Lti13Cache when I call LtiOidcLogin, and have to add in LtiServiceConnector when I call LtiMessageLaunch e.g 

- in LtiController (From: `Route::match(['get', 'post'], '/lti-login', [LtiController::class, 'ltiLogin']`):

`$lti_login = LtiOidcLogin::new(new Lti13Database(), new Lti13Cache(), new Lti13Cookie());`

- and in LaunchController.php (From: `Route::match(['post'], '/launch', [LaunchController::class, 'view'])->middleware('auth:lti')` where lti is a Guard):

`$launch = LtiMessageLaunch::fromCache($launch_id, new Lti13Database(),new Lti13Cache(),new LtiServiceConnector(app(ICache::class), new Client(['timeout' => 30])));`

It all seems to be working when I do this, but I have a feeling that:

1. I shouldn't need instances of all three/four for every call?
2. I should be able to create them once and pick them up when needed?

Sorry if I'm being dim!

**Comment by dbhynds** [comment]
Good question. Here's how we handle that.

In the `ServiceProvider` for our app, we bind our implementations to the interfaces provided in the library:
```php
$this->app->bind(ICache::class, Lti13Cache::class);
$this->app->bind(ICookie::class, Lti13Cookie::class);
$this->app->bind(IDatabase::class, LtiRepository::class);
$this->app->bind(ILtiServiceConnector::class, function () {
    return new LtiServiceConnector(app(ICache::class), new Client([
        'timeout' => 30,
    ]));
});
```

Then, anytime Laravel sees that interface being references in an constructor, it will resolve it from the app container. So then if an object we're using needs an `LtiOidcLogin` object, we can similarly just do:
```php
$lti_login = app(LtiOidcLogin::class);
```

For the launch example you cited, we do it slightly differently. We have a service that basically does this:
```php
class Lti13Service
{
    public function __construct(
        private IDatabase $db,
        private ICache $cache,
        private ICookie $cookie,
        private ILtiServiceConnector $serviceConnector)
    {}

    public function validateLaunch(array $requestData): LtiMessageLaunch
    {
        return LtiMessageLaunch::new($this->db, $this->cache, $this->cookie, $this->serviceConnector)
            ->validate($requestData);
    }
}
```

So all we have to do to validate a launch is:
```php
$validatedLaunch = app(Lti13Service::class)->validateLaunch($dataFromARequest);
```
