### ISSUE TITLE
ParseError on PHP 7.4 when using LtiServiceConnector

### ISSUE THREAD

**Issue by Lokilein** [packbackbooks/lti-1-3-php-library#66]
Using the LTIServiceConnector does not work currently with PHP 7. 4, based on a unneccessary trailing comma in Line 157 of src/LtiServiceConnector:

`    public function getAll(
        ILtiRegistration $registration,
        array $scopes,
        IServiceRequest $request,
        string $key = null,
    ): array`

Causing the message: ParseError: syntax error, unexpected ')', expecting variable (T_VARIABLE) in LtiServiceConnector.php on line 157

Removing the "," after the "key = null" would make it usable for PHP 7.4.

**Comment by dbhynds** [comment]
This was fixed in v5.2.0
