### ISSUE TITLE
Issues with Laravel implementation

### ISSUE THREAD

**Issue by ZeroThe2nd** [packbackbooks/lti-1-3-php-library#68]
First off as a note: I'm totally new to LTI as a standard, however I am familiar with Laravel and REST APIs.

Currently, I'm working on an implementation of this library to integrate our e-learning platform as an LTI Tool with other LTI platforms. Following the implementation guide, I'm now as far as having some routes for the authentication flow, however it's never made clear how/where/which endpoints should exist.

Currently, the following endpoints have been made using the example:

|method|url|purpose|
|---|---|---|
|`POST`|`/lti/auth`|Login Endpoint|
|`POST`|`/lti/launch`|LTI Launch Endpoint?|

Aside these endpoints, I have no further clue of what endpoints I need to make, and if the URLs I have for my existing endpoints are even remotely correct. This can't be found in the readme or wiki either, not in any documentation I can find on the IMS Global website.

Aside this, the LTI registration class requires some fields to be set according to the documentation, but I'm not 100% sure what data needs to be in there:

```php
return LtiRegistration::new()
    ->setAuthTokenUrl($iss->auth_token_url)      // URL to my auth endpoint? so /lti/auth?
    ->setAuthLoginUrl($iss->auth_login_url)      // URL to my launch endpoint? /lti/launch?
    ->setClientId($iss->client_id)               // Client ID, I assume OAuth client_id here? Assuming this must be unique for every platform connecting to this tool?
    ->setKeySetUrl($iss->key_set_url)            // JWKs endpoint to get the Key Set
    ->setKid($iss->kid)                          // Key ID to use from the JWKs endpoint
    ->setIssuer($iss->issuer)                    // Issuer model instance (as array?) returned from the Database class implementation?
    ->setToolPrivateKey($iss->tool_private_key); // String content of the Private Key generated for my tool (must it match the JWKs private key specified by the Key ID?)
```

If there's any additional information available on how this should be implemented, I'd love to hear about it. Or maybe an example project or such that I could use for further reading and information?

**Comment by Stunext** [comment]
Hello! Same issue here!

**Comment by dbhynds** [comment]
If you're using an services that require you to authenticate with the LMS (such as AGS, NRPS, etc.), you will need to also create a  JWKS endpoint. (We have a `GET /api/jwks/{id}` endpoint, for example).

Beyond that, it really depends on what your app is trying to do, what and information you need. If you could provide a little more information about what you're trying to achieve, I could probably offer some suggestions.

If it helps to get you started, here's the abridged version of how our launch endpoint works:
```php
    public function launch(Request $request)
    {
        $launch = LtiMessageLaunch::new($this->db, $this->cache, $this->cookie, $this->serviceConnector)
            ->validate($request->all());
        $ltiData = $launch->getLaunchData();
        // Now we have all of the data in the LTI launch, including information about the user, course, role, etc.
        // We save the stuff we need in the database and redirect the user to the appropriate place.
    }

```

**Comment by jacksontong** [comment]
Could you please give us a full endpoints demo?
I also have some other questions:

1. How do I generate jwks like this one https://applications.zoom.us/lti/advantage/jwks
2. What is the database structure for issuer and deployment?
3. What is the corresponding endpoint for Redirect URIs, Target Link URI and OpenID Connect Initiation Url?

![image](https://user-images.githubusercontent.com/7871218/225928775-07d17119-c865-40f8-bd3e-2c9593e554e1.png)

I'm totally new to LTI, my goal is to make my laravel app up and running inside canvas.

**Comment by dbhynds** [comment]
When I have time someday, I'll make a sample implementation.

1) For the JWKS URL, it needs to have the ID of the issuer (e.g. `https://example.com/jwks/{issuerId}`). From there you can generate JWKS based on the given issuer using the `jwks` function in this sample implementation: https://github.com/packbackbooks/lti-1-3-php-library/wiki/Laravel-Implementation-Guide#lti13service

2) Here's the basic database structure for issuers, deployments etc.

Issuer:

- id
- issuer
- client_id
- auth_token_url
- auth_login_url
- auth_server
- key_set_url
- tool_private_key
- kid

Deployments:

- id
- issuer_id (foreign)
- deployment_id

3) For redirect link URI and target link URI, we use our launch endpoint (e.g. `https://example.com/launch`) that implements the code described here: https://github.com/packbackbooks/lti-1-3-php-library/wiki/Endpoints-and-Handling-Requests#lti-message-launches. For the OIDC Initiation URL we use our login endpoint (e.g. `https://example.com/login`) which implements the code described here: https://github.com/packbackbooks/lti-1-3-php-library/wiki/Endpoints-and-Handling-Requests#open-id-connect-login-request
